### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by jjwwno** [Wu-Junran/SEP#2]
ValueError: Encountered tensor with size 311 in dimension -2, but expected size 80

**Comment by Wu-Junran** [comment]
有一说一，你就这么给个描述，我咋知道你怎么遇上这个问题的

**Comment by jjwwno** [comment]
C:\Users\Charming\PycharmProjects\pythonProject1\venv\Scripts\python.exe C:/axi/SEP-master/SEPG/trainer_sep_args.py
IMDB-BINARY	GCN	3	sum	64	16	0.5	1	False
Traceback (most recent call last):
  File "C:/axi/SEP-master/SEPG/trainer_sep_args.py", line 266, in <module>
    trainer.train()
  File "C:/axi/SEP-master/SEPG/trainer_sep_args.py", line 157, in train
    out = self.model(batch)
  File "C:\Users\Charming\PycharmProjects\pythonProject1\venv\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\axi\SEP-master\SEPG\sep.py", line 167, in forward
    x = F.relu(self.sepools[_](x, edge_index, size=size))
  File "C:\Users\Charming\PycharmProjects\pythonProject1\venv\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\axi\SEP-master\SEPG\sep.py", line 36, in forward
    out = self.propagate(edge_index, x=x, size=size)
  File "C:\Users\Charming\PycharmProjects\pythonProject1\venv\lib\site-packages\torch_geometric\nn\conv\message_passing.py", line 367, in propagate
    size, kwargs)
  File "C:\Users\Charming\PycharmProjects\pythonProject1\venv\lib\site-packages\torch_geometric\nn\conv\message_passing.py", line 259, in __collect__
    self.__set_size__(size, dim, data)
  File "C:\Users\Charming\PycharmProjects\pythonProject1\venv\lib\site-packages\torch_geometric\nn\conv\message_passing.py", line 224, in __set_size__
    (f'Encountered tensor with size {src.size(self.node_dim)} in '
ValueError: Encountered tensor with size 311 in dimension -2, but expected size 80.

**Comment by jjwwno** [comment]
这就是在运行过程中报的错误

**Comment by Wu-Junran** [comment]
运行环境是否一致呢？

主要是：PyTorch Geometric 2.0.1

我自己更新到最新版本（2.0.3）之后也跑不起来，目前因为能用就一直在2.0.1上跑的，没做最新的适配

**Comment by 17qingyu** [comment]
不是环境问题，作者的sep flow是"target_to_source"，但是propagate的size是按source_to_traget计算的，导致最后传入的size不同，把propagate中的size=size改成size=[[1,0]]就可以了

**Comment by moxiaoshao** [comment]
您好，请教一下：
我的编译环境是按照readme的版本要求装的。SEPN代码可以跑，但是SEPG中执行到第二步：python trainer_sep_args.py --dataset IMDB-BINARY --hidden_dim 64 --batch_size 128 --final_dropout 0 --lr_schedule 
会有以下报错：
---------------------------------------------------------------------
IMDB-BINARY    GCN    3    sum    64    128    0.0    1    True
Traceback (most recent call last):
  File "trainer_sep_args.py", line 271, in <module>
    trainer.train()
  File "trainer_sep_args.py", line 180, in train
    checkpoint = torch.load('./checkpoints/{}/experiment-{}_fold-{}_seed-{}_best-model.pth'.format(self.log_folder_name, self.exp_name, fold_number, self.args.seed))
  File "/home/anaconda3/envs/pytorch_sep/lib/python3.7/site-packages/torch/serialization.py", line 579, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/anaconda3/envs/pytorch_sep/lib/python3.7/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/anaconda3/envs/pytorch_sep/lib/python3.7/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] 没有那个文件或目录: './checkpoints/IMDB-BINARY/SEP/experiment-GNN=GCN_TD=3_GP=sum_BS=128_HD=64_LR=0.0005_WD=0.0001_GN=1.0_DO=0.0_LS=True_TS=2023-11-01-13:00:45_fold-1_seed-0_best-model.pth'
-----------------------------------------------------------------------
找了一下，目录确实没有，只有./checkpoints/IMDB-BINARY/SEP，不知道是什么原因呢？

**Comment by chen-ysh** [comment]
> size=[[1,0]]

请问可以具体说一下改哪一个吗，有好几个地方有 size=size

**Comment by chenx-hi** [comment]
> > 大小=[[1,0]]
> 
> 请问可以具体说一下改哪一个吗，有好几个地方有size=size

在SEPooling下的out = self.propagate(edge_index, x=x, size=size[[1,0]])
