### ISSUE TITLE
问题请教

### ISSUE THREAD

**Issue by Albertvicient** [Wu-Junran/SEP#4]
你好，我在运行代码的时候出现了一个问题，想跟您请教一下。我应该如何解决这个问题。
Traceback (most recent call last):
  File "trainer_sep_args.py", line 11, in <module>
    from sep import SEP
  File "/home/sunhao/SEPG/sep.py", line 10, in <module>
    from torch_geometric.nn import GCNConv
  File "/home/sunhao/anaconda3/envs/SEPG/lib/python3.7/site-packages/torch_geometric/__init__.py", line 4, in <module>
    import torch_geometric.data
  File "/home/sunhao/anaconda3/envs/SEPG/lib/python3.7/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/home/sunhao/anaconda3/envs/SEPG/lib/python3.7/site-packages/torch_geometric/data/data.py", line 20, in <module>
    from torch_sparse import SparseTensor
  File "/home/sunhao/anaconda3/envs/SEPG/lib/python3.7/site-packages/torch_sparse/__init__.py", line 41, in <module>
    from .tensor import SparseTensor  # noqa
  File "/home/sunhao/anaconda3/envs/SEPG/lib/python3.7/site-packages/torch_sparse/tensor.py", line 13, in <module>
    class SparseTensor(object):
  File "/home/sunhao/anaconda3/envs/SEPG/lib/python3.7/site-packages/torch/jit/_script.py", line 974, in script
    _compile_and_register_class(obj, _rcb, qualified_name)
  File "/home/sunhao/anaconda3/envs/SEPG/lib/python3.7/site-packages/torch/jit/_script.py", line 67, in _compile_and_register_class
    torch._C._jit_script_class_compile(qualified_name, ast, defaults, rcb)
RuntimeError:
Tried to access nonexistent attribute or method 'crow_indices' of type 'Tensor'.:
  File "/home/sunhao/anaconda3/envs/SEPG/lib/python3.7/site-packages/torch_sparse/tensor.py", line 109
    def from_torch_sparse_csr_tensor(self, mat: torch.Tensor,
                                     has_value: bool = True):
        rowptr = mat.crow_indices()
                 ~~~~~~~~~~~~~~~~ <--- HERE
        col = mat.col_indices()

我安装的版本如下：
![1668738024524](https://user-images.githubusercontent.com/43636105/202601855-234221f5-5cdd-47d0-a8d6-bb2425e01198.png)

**Comment by Wu-Junran** [comment]
看你配置的torch-geometric版本应该是2.1.0.

我目前运行的版本是：2.0.1

这个哥们跟你的问题差不多，https://github.com/Wu-Junran/SEP/issues/2

**Comment by Albertvicient** [comment]
感谢指导，还想请教一下，就是数据集里面的.mat的格式数据没有用到是么？如果换数据集的话只需要txt的文件了是么？

**Comment by Albertvicient** [comment]
我认为你的工作非常有意义，我在运行自己的数据集的时候遇到了一个问题，就是如下所示
![1668748161638](https://user-images.githubusercontent.com/43636105/202624258-4e5fce03-22c7-4c23-9131-0cf025e5a4d5.png)
请问有什么解决的建议么，谢谢

**Comment by Wu-Junran** [comment]
关于txt，其实是之前文章在GIN源代码基础上改的，因此保留了数据处理的方式。如果你有自己的数据的话，其实只要load_graph这个函数的输出能对的上就行。

关于图片里的这个问题，我感觉应该是你数据里有某个图存在孤立节点，导致取对数的时候报错了

**Comment by Albertvicient** [comment]
感谢您的回答，我再继续检查自己的数据，再次表示感谢！
